global:
  # Important to note, that scrape times > 5minutes can't be handled
  # by grafana gracefully and will be treated as scarce metrics
  scrape_interval:  5m # By default, scrape targets every 15 seconds.
  scrape_timeout: 300ms

scrape_configs:
  - job_name: pagespeed_exporter_metrics
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'pagespeed_exporter:9271'

  - job_name: pagespeed_exporter_probe
    metrics_path: /probe
    # Re-Label configurations so that we can use them
    # to configure the pagespeed exporter
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: "pagespeed_exporter:9271"
    static_configs:
      - targets:
          - 'https://github.com/foomo/'
          - '{"url":"https://github.com/foomo/pagespeed_exporter","strategy":"mobile"}'
